all:
	cd build; \
	g++ -isystem /usr/local/include ../main.cpp -std=c++11 -O0 -g -Wall -o klcp_tool

prod:
	cd build; \
        g++ -isystem /usr/local/include ../main.cpp -std=c++11 -Ofast -o klcp_tool
